### ISSUE TITLE
I hope that the code will be publish soon

### ISSUE THREAD

**Issue by vanetspark** [jlian2/Robust-Voice-Style-Transfer#2]

**Comment by jlian2** [comment]
Hi! To reply in general, we would encourage you to implement the code by yourself if you plan to immediately run it. We can not say too much about that due to copyright issue. But probably we will not release it until next year.

Model and implementation details is in our most recent paper:
https://arxiv.org/abs/2205.05227
https://arxiv.org/abs/2206.02512

Thanks

**Comment by jvel07** [comment]
Hi @jlian2, congrats on the paper, very insightful. I will start investigations on audio-style transfer and would love to have your paper reproduced. Do you happen to have any updates on the code related?
